#!/bin/bash
# ChainCacao - Network Verification Script

set -e

# Get the directory where the script is located
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT_DIR="$(cd "$DIR/.." && pwd)"

BLOCKCHAIN_DIR="$ROOT_DIR"
NETWORK_DIR="$ROOT_DIR/network"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

println() {
  echo -e "${BLUE}==>${NC} $1"
}

success() {
  echo -e "${GREEN}✓${NC} $1"
}

warning() {
  echo -e "${YELLOW}⚠${NC} $1"
}

error() {
  echo -e "${RED}✗${NC} $1"
}

# Check crypto-config.yaml
check_crypto_config() {
  println "Checking crypto-config.yaml..."

  if [ ! -f "$NETWORK_DIR/crypto-config.yaml" ]; then
    error "crypto-config.yaml not found"
    return 1
  fi

  # Check for single orderer
  if ! grep -q "Hostname: orderer" "$NETWORK_DIR/crypto-config.yaml"; then
    error "Orderer hostname should be 'orderer'"
    return 1
  fi

  # Check for NodeOUs
  if ! grep -q "EnableNodeOUs: true" "$NETWORK_DIR/crypto-config.yaml"; then
    warning "NodeOUs not enabled for all organizations"
  fi

  success "crypto-config.yaml looks good"
}

# Check configtx.yaml
check_configtx() {
  println "Checking configtx.yaml..."

  if [ ! -f "$NETWORK_DIR/configtx.yaml" ]; then
    error "configtx.yaml not found"
    return 1
  fi

  # Check for single orderer in addresses
  if grep -q "orderer[0-9]*\.chaincacao\.com" "$NETWORK_DIR/configtx.yaml" | grep -v "orderer.chaincacao.com"; then
    error "Multiple orderers found in configtx.yaml"
    return 1
  fi

  # Check for etcdraft configuration
  if ! grep -q "OrdererType: etcdraft" "$NETWORK_DIR/configtx.yaml"; then
    error "OrdererType not set to etcdraft"
    return 1
  fi

  # Check for single consenter
  CONSENTER_COUNT=$(grep -c "Host: orderer.chaincacao.com" "$NETWORK_DIR/configtx.yaml")
  if [ "$CONSENTER_COUNT" -ne 1 ]; then
    error "Expected 1 consenter, found $CONSENTER_COUNT"
    return 1
  fi

  # Check profiles
  if ! grep -q "ChainCacaoOrdererGenesis:" "$NETWORK_DIR/configtx.yaml"; then
    error "ChainCacaoOrdererGenesis profile not found"
    return 1
  fi

  if ! grep -q "ChainCacaoChannel:" "$NETWORK_DIR/configtx.yaml"; then
    error "ChainCacaoChannel profile not found"
    return 1
  fi

  success "configtx.yaml looks good"
}

# Check generated certificates from Fabric CA
check_certificates() {
  println "Checking certificates generated by Fabric CA..."

  if [ ! -d "$BLOCKCHAIN_DIR/organizations" ]; then
    error "organizations directory not found - certificates not generated"
    return 1
  fi

  # Check orderer certificates
  ORDERER_MSP="$BLOCKCHAIN_DIR/organizations/ordererOrganizations/chaincacao.com/orderers/orderer.chaincacao.com/msp"
  if [ ! -d "$ORDERER_MSP" ]; then
    error "Orderer MSP directory not found"
    return 1
  fi

  # Check peer certificates for each org
  ORGS=("producteurs" "exportateurs" "certif" "ministere" "transformateurs")
  for org in "${ORGS[@]}"; do
    PEER_MSP="$BLOCKCHAIN_DIR/organizations/peerOrganizations/$org.chaincacao.com/peers/peer0.$org.chaincacao.com/msp"
    if [ ! -d "$PEER_MSP" ]; then
      error "Peer MSP directory not found for $org"
      return 1
    fi
  done

  success "All certificates generated by Fabric CA found"
}

# Check genesis block
check_genesis() {
  println "Checking genesis block..."

  GENESIS_FILE="$NETWORK_DIR/system-genesis-block/genesis.block"
  if [ ! -f "$GENESIS_FILE" ]; then
    error "Genesis block not found - run genesis generation first"
    return 1
  fi

  # Check file size (should be > 0)
  if [ ! -s "$GENESIS_FILE" ]; then
    error "Genesis block is empty"
    return 1
  fi

  success "Genesis block created successfully"
}

# Check Docker containers
check_containers() {
  println "Checking Docker containers..."

  # Check if containers are running
  RUNNING_CONTAINERS=$(docker ps --filter "name=chaincacao" --format "{{.Names}}" | wc -l)
  if [ "$RUNNING_CONTAINERS" -lt 6 ]; then
    warning "Expected 6 containers (1 orderer + 5 peers), found $RUNNING_CONTAINERS"
  else
    success "All containers are running"
  fi

  # List containers
  docker ps --filter "name=chaincacao" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
}

# Check live channel status
check_channel_status() {
  println "Checking live channel status..."
  
  if ! docker exec cli peer channel list 2>/dev/null | grep -q "chaincacaochannel"; then
    warning "Peers have not joined 'chaincacaochannel' yet or CLI is not ready."
  else
    success "Peers are successfully joined to 'chaincacaochannel'"
  fi
}

# Main execution
main() {
  println "ChainCacao Network Verification"
  println "==============================="

  cd "$BLOCKCHAIN_DIR"

  check_crypto_config
  check_configtx
  check_certificates
  check_genesis
  check_containers
  check_channel_status

  println ""
  success "Verification completed!"
}

main "$@"